### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by bmintz** [slice/queuebot#14]
It's not ~~open source~~ free software till you add a license. I recommend AGPLv3 because it requires you to publish the source code whenever you update the bot server.

**Comment by slice** [comment]
I'll opt for MIT since queuebot uses large amounts of code from [Mousey](https://github.com/FrostLuma/Mousey).

**Comment by bmintz** [comment]
MIT does not require use of any particular license so I don't see how that makes a difference.

**Comment by slice** [comment]
Eh...It's permissive enough for my tastes. '
